version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ideasoft
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - laravel
    depends_on:
      - mysql
    env_file: .env
    command: ["php", "artisan", "serve", "--host=0.0.0.0", "--port=8000"]
    ports:
      - "8000:8000"
    links:
      - mysql
    entrypoint: ["bash", "-c", "composer install && php artisan migrate --force && php artisan db:seed && php artisan serve --host=0.0.0.0 --port=8000"]

  mysql:
    image: mysql:5.7
    container_name: ideasoft-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ideasoft
      MYSQL_USER: ideasoft
      MYSQL_PASSWORD: Xas615das
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - laravel

networks:
  laravel:

volumes:
  mysql-data:
